In [1]:
import pandas

In [2]:
df = pandas.read_excel('RSNA.xlsx')
df.head(10)

,Summe von Label,Spaltenbeschriftungen,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Zeilenbeschriftungen,any,epidural,intraparenchymal,intraventricular,subarachnoid,subdural,Summe
1,ID_000039fa0,0,0,0,0,0,0,0
2,ID_00005679d,0,0,0,0,0,0,0
3,ID_00008ce3c,0,0,0,0,0,0,0
4,ID_0000950d7,0,0,0,0,0,0,0
5,ID_0000aee4b,0,0,0,0,0,0,0
6,ID_0000f1657,0,0,0,0,0,0,0
7,ID_000178e76,0,0,0,0,0,0,0
8,ID_00019828f,0,0,0,0,0,0,0
9,ID_0001dcc25,0,0,0,0,0,0,0

In [3]:
new_header = df.iloc[0] 

df = df[1:] 

df.columns = new_header

In [4]:
df.head()

,Zeilenbeschriftungen,any,epidural,intraparenchymal,intraventricular,subarachnoid,subdural,Summe
1,ID_000039fa0,0,0,0,0,0,0,0
2,ID_00005679d,0,0,0,0,0,0,0
3,ID_00008ce3c,0,0,0,0,0,0,0
4,ID_0000950d7,0,0,0,0,0,0,0
5,ID_0000aee4b,0,0,0,0,0,0,0

In [5]:
del df['Summe']
df.head()

,Zeilenbeschriftungen,any,epidural,intraparenchymal,intraventricular,subarachnoid,subdural
1,ID_000039fa0,0,0,0,0,0,0
2,ID_00005679d,0,0,0,0,0,0
3,ID_00008ce3c,0,0,0,0,0,0
4,ID_0000950d7,0,0,0,0,0,0
5,ID_0000aee4b,0,0,0,0,0,0

In [6]:
df.columns = ['ID','Any','Epidural','Intraparenchymal','Intraventricular','Subarachnoid','Subdural']
df.head()

,ID,Any,Epidural,Intraparenchymal,Intraventricular,Subarachnoid,Subdural
1,ID_000039fa0,0,0,0,0,0,0
2,ID_00005679d,0,0,0,0,0,0
3,ID_00008ce3c,0,0,0,0,0,0
4,ID_0000950d7,0,0,0,0,0,0
5,ID_0000aee4b,0,0,0,0,0,0

In [7]:
df.to_csv('RSNA.csv',index=False)